### ISSUE TITLE
Dirty Codebase (Website Only)

### ISSUE THREAD

**Issue by ghost** [reactxsw/Smilewinbot#28]
I know you are all working on making the bots codebase cleaner. I just wanted to say, as a first time contributor to this repo, **the code is very messy**. The HTML could definitely be more intuitive, and the use of CSS is not very programmatic. As @reactxsw said you guys are new to the front-end side of web development; I just think for any contributors sake, the codebase should be cleaned up.

**Comment by siqnole** [comment]
vouch ^^
