### ISSUE TITLE
Website title

### ISSUE THREAD

**Issue by siqnole** [reactxsw/Smilewinbot#35]
your title on the website (the one that changes from S, Sm, Smi, to Smile) makes the webpage incredibly laggy on less "beefy" hardware, this makes it a problem for mobile users, and chromebook users (i tested it on my chromebook and some old laptops)

**Comment by ghost** [comment]
Yeah the websites load time is very slow, and that is one of the variables of the situation. Having things like that for aesthetic purposes only is usually a really bad idea.

**Comment by ghost** [comment]
Another issue is bootstrap; bootstrap CSS imports all of the premade classes, slowing down load times by a lot. 
### Fix
A fix to this would be using something like tailwind, which purges all unused CSS to help fix that load time issue.

**Comment by siqnole** [comment]
should be fixed, will update you if else.
